=== otcz/Vulcano2.0/src/com/company/addons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="addonConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="addons" type="Addons"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Addons">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="include">
          <xs:annotation>
            <xs:documentation>
              <p>Other addons files can be included using this tag. The addons listed in the specified file will
                be inserted at this point in the addons file.</p>
              <p>The filenames specified in this element should be relative to the current working directory or
                to the classpath</p>
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="addon">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="priority" type="PriorityType" minOccurs="0"/>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="class" type="xs:string"/>
              <xs:element name="configFile" type="xs:string" minOccurs="0"/>
              <xs:element name="luciadMapOptions" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="PriorityType">
    <xs:annotation>
      <xs:documentation>
        <p>The priority of the addons determine the order in which they are plugged into Lucy.
          Addons with a low priority number are plugged earlier into Lucy.</p>

        <p>The priority should be an integer, or one of the following strings:</p>
        <ul>
          <li>early: corresponds to integer value 0. Use this value if your addon needs
          to be plugged in before most other addons. For instance, the TLcyPersistentPreferencesAddOn uses
          this priority, as the other addons may need the preferences when they are plugged in.</li>

          <li>data_producer (value 5.000): Use this value if, for instance, your addon registers decoders for data
            formats. For instance, implementations of ALcyFormatAddOn should use this priority.</li>

          <li>data_consumer (value 9.000): Use this value if your addon needs to decode data files. For instance,
          when your addon uses TLcyDataFormatManager#handleDataSources, use this priority.</li>

          <li>default (value 10.000): default priority. Use this if your addon does not have any special order
          requirements.</li>

          <li>late (value 100.000): use this value if your addon needs to be loaded after all other addons. For 
          instance, the TLcyWorkspaceAddOn uses this priority as it needs to restore the state of all other addons
          when Lucy starts up.</li>
        </ul>
      </xs:documentation>
    </xs:annotation>
    <xs:union memberTypes="xs:integer">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="early"/>
          <xs:enumeration value="data_producer"/>
          <xs:enumeration value="data_consumer"/>
          <xs:enumeration value="default"/>
          <xs:enumeration value="late"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
</xs:schema>

=== otcz/Vulcano2.0/src/lucy/addons.xml
<?xml version="1.0" encoding="UTF-8"?>
<addonConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="addons.xsd">
  <!--
    Default add-ons file for a Lightspeed based Lucy.
    -->
  <addons>

    <include>lucy/addons_common.xml</include>

    <!--
      Add-ons or add-on configurations specific for when the Lightspeed map is the main view.
      -->

    <addon>
      <priority>data_consumer</priority>
      <name>Lightspeed Map</name>
      <class>com.luciad.lucy.addons.lspmap.TLcyLspMapAddOn</class>
      <configFile>lucy/lspmap/TLcyLspMapAddOn.cfg</configFile>
      <!--Don't check for the Lightspeed option, you should get an explicit license error
       when using this addon in LuciadLightspeed LM -->
    </addon>
    <addon>

      <priority>data_producer</priority>
      <name>ESRI ArcInfo ASCII Grid Format</name>
      <class>com.luciad.lucy.addons.arcinfoasciigrid.TLcyArcInfoASCIIGridFormatAddOn</class>
      <configFile>lucy/arcinfoasciigrid/TLcyArcInfoASCIIGridFormatAddOn.cfg</configFile>
    </addon>
    <addon>
      <!--
        Priority is 'late' to allow other add-ons to register workspace codecs before the
        first workspace is loaded.
      -->
      <priority>late</priority>
      <name>Workspace</name>
      <class>com.luciad.lucy.addons.workspace.TLcyWorkspaceAddon</class>
      <configFile>lucy/workspace/workspace_addon.cfg</configFile>
    </addon>

    <addon>
      <name>Hello World</name>
      <class>com.company.HelloWorldAddOn</class>
    </addon>

  </addons>

</addonConfiguration>

=== otcz/Vulcano2.0/src/com/company/addons_common.xml
<?xml version="1.0" encoding="UTF-8"?>
<addonConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="addons.xsd">
  <!--
    Add-ons that can be used in both a GXY or Lightspeed based Lucy application.
    -->
  <addons>
    <include>com/company/addons_data.xml</include>
    <addon>
      <!--
        The priority is 'early' because other add-ons might need
        the preferences to properly initialize
      -->
      <priority>early</priority>
      <name>Preferences</name>
      <class>com.luciad.lucy.addons.preferences.TLcyPersistentPreferencesAddOn</class>
      <configFile>lucy/preferences/preferences_addon.cfg</configFile>
    </addon>
    <addon>
      <priority>early</priority>
      <name>Look and Feel</name>
      <class>com.luciad.lucy.addons.lookandfeel.TLcyLookAndFeelAddOn</class>
      <configFile>lucy/lookandfeel/lookandfeel_addon.cfg</configFile>
    </addon>
    <addon>
      <priority>early</priority>
      <name/>
      <!-- No name, to avoid that it shows up in the UI -->
      <class>com.luciad.lucy.addons.debug.TLcyDebugAddOn</class>
      <configFile>lucy/debug/TLcyDebugAddOn.cfg</configFile>
    </addon>
    <addon>
      <!--
        Network Connection add-on should be loaded early to ensure
        the settings are active before any HTTP connection is attempted
      -->
      <priority>early</priority>
      <name>Network Connection</name>
      <class>com.luciad.lucy.addons.networkconnection.TLcyNetworkConnectionAddOn</class>
      <configFile>lucy/networkconnection/TLcyNetworkConnectionAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Dimensional Filter AddOn</name>
      <class>com.luciad.lucy.addons.dimensionalfilter.TLcyDimensionalFilterAddOn</class>
      <configFile>lucy/dimensionalfilter/TLcyDimensionalFilterAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>About Box</name>
      <class>com.luciad.lucy.addons.about.TLcyAboutBoxAddon</class>
      <configFile>lucy/about/about_box_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Help</name>
      <class>com.luciad.lucy.addons.help.TLcyHelpAddOn</class>
      <configFile>lucy/help/TLcyHelpAddOn.cfg</configFile>
    </addon>
    <addon>
      <priority>data_producer</priority>
      <name>Geo References</name>
      <class>com.luciad.lucy.addons.modelreference.TLcyModelReferenceAddOn</class>
      <configFile>lucy/modelreference/modelreference_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Hyperlink</name>
      <class>com.luciad.lucy.addons.hyperlink.TLcyHyperlinkAddOn</class>
    </addon>
    <addon>
      <name>Aircraft Performance Settings</name>
      <class>com.luciad.lucy.addons.aps.TLcyAPSAddOn</class>
      <configFile>lucy/aps/apsAddOn.cfg</configFile>
      <luciadMapOptions>AIS</luciadMapOptions>
    </addon>
    <addon>
      <name>Magnetic North Calculation</name>
      <class>com.luciad.lucy.addons.magneticnorth.TLcyMagneticNorthAddOn</class>
      <configFile>lucy/magneticnorth/magneticnorth_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Layer Control</name>
      <class>com.luciad.lucy.addons.layercontrol.TLcyLayerControlAddOn</class>
      <configFile>lucy/layercontrol/TLcyLayerControlAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Edit Units</name>
      <class>com.luciad.lucy.addons.map.TLcyMapEditUnitAddOn</class>
      <configFile>lucy/map/map_units.cfg</configFile>
    </addon>
    <addon>
      <name>Object Properties Comparison</name>
      <class>com.luciad.lucy.addons.comparison.TLcyObjectPropertiesComparisonAddOn</class>
      <configFile>lucy/comparison/TLcyObjectPropertiesComparisonAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Selection Editor</name>
      <class>com.luciad.lucy.addons.selectioneditor.TLcySelectionEditorAddOn</class>
      <configFile>lucy/selectioneditor/selectioneditor.cfg</configFile>
    </addon>
    <addon>
      <name>Grid Coordinate</name>
      <class>com.luciad.lucy.addons.gridcoordinate.TLcyGridCoordinateAddOn</class>
      <configFile>lucy/gridcoordinate/gridcoordinate_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Format Bar</name>
      <class>com.luciad.lucy.addons.formatbar.TLcyFormatBarAddOn</class>
      <configFile>lucy/formatbar/TLcyFormatBarAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Model Customizer</name>
      <class>com.luciad.lucy.addons.modelcustomizer.TLcyModelCustomizerAddOn</class>
      <configFile>lucy/modelcustomizer/TLcyModelCustomizerAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Tote</name>
      <class>com.luciad.lucy.addons.tote.TLcyToteAddOn</class>
      <configFile>lucy/tote/tote_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Tote Lightspeed</name>
      <class>com.luciad.lucy.addons.tote.lightspeed.TLcyLspToteAddOn</class>
      <configFile>lucy/tote/lsp/TLcyLspToteAddOn.cfg</configFile>
      <luciadMapOptions>Lightspeed</luciadMapOptions>
    </addon>
    <addon>
      <name>Tree Table View</name>
      <class>com.luciad.lucy.addons.treetable.TLcyTreeTableViewAddOn</class>
      <configFile>lucy/treetable/TLcyTreeTableViewAddOn.cfg</configFile>
    </addon>
    <!--
      When loading this add-on, the TLcyPreviewAddOn is also required. This
      add-on should be loaded before the TLcyPreviewAddOn
    -->
    <addon>
      <name>Lightspeed Previewer</name>
      <class>com.luciad.lucy.addons.previewer.lightspeed.TLcyLspPreviewAddOn</class>
      <configFile>lucy/previewer/lightspeed/TLcyLspPreviewAddOn.cfg</configFile>
      <luciadMapOptions>Realtime, Lightspeed</luciadMapOptions>
    </addon>
    <addon>
      <name>Previewer</name>
      <class>com.luciad.lucy.addons.previewer.TLcyPreviewAddOn</class>
      <configFile>lucy/previewer/previewer.cfg</configFile>
      <luciadMapOptions>Realtime</luciadMapOptions>
    </addon>
    <addon>
      <name>Vertical View</name>
      <class>com.luciad.lucy.addons.vertical.TLcyVerticalViewAddOn</class>
      <configFile>lucy/vertical/verticalview_addon.cfg</configFile>
    </addon>
    <addon>
      <priority>early</priority>
      <name>Lightspeed Style Repository</name>
      <class>com.luciad.lucy.addons.stylerepository.lightspeed.TLcyLspStyleRepositoryAddOn</class>
      <configFile>lucy/stylerepository/lightspeed/TLcyLspStyleRepositoryAddOn.cfg</configFile>
      <luciadMapOptions>Lightspeed</luciadMapOptions>
    </addon>

    <addon>
      <name>Lightspeed Grid Coordinate</name>
      <class>com.luciad.lucy.addons.gridcoordinate.lightspeed.TLcyLspGridCoordinateAddOn</class>
      <luciadMapOptions>Lightspeed</luciadMapOptions>
    </addon>
    <addon>
      <name>Lightspeed Printing</name>
      <class>com.luciad.lucy.addons.print.lightspeed.TLcyLspPrintAddOn</class>
      <configFile>lucy/print/lightspeed/TLcyLspPrintAddOn.cfg</configFile>
      <luciadMapOptions>Lightspeed</luciadMapOptions>
    </addon>
    <addon>
      <name>Undo</name>
      <class>com.luciad.lucy.addons.undo.TLcyUndoAddOn</class>
      <configFile>lucy/undo/undo_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Copy Paste</name>
      <class>com.luciad.lucy.addons.datatransfer.TLcyCopyPasteAddOn</class>
      <configFile>lucy/datatransfer/copy_paste_addon.cfg</configFile>
    </addon>
    <addon>
      <name>Generic map</name>
      <class>com.luciad.lucy.addons.genericmap.TLcyGenericMapAddOn</class>
      <configFile>lucy/genericmap/TLcyGenericMapAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Connection</name>
      <class>com.luciad.lucy.addons.connection.TLcyConnectionAddOn</class>
      <configFile>lucy/connection/TLcyConnectionAddOn.cfg</configFile>
    </addon>
    <addon>
      <name>Lightspeed Layer Customizer</name>
      <class>com.luciad.lucy.addons.layercustomizer.lightspeed.TLcyLspLayerCustomizerAddOn</class>
      <luciadMapOptions>Lightspeed</luciadMapOptions>
    </addon>
    <addon>
      <name>Lightspeed Camera Linking</name>
      <class>com.luciad.lucy.addons.cameralinking.lightspeed.TLcyLspCameraLinkAddOn</class>
      <configFile>lucy/cameralinking/lightspeed/TLcyLspCameraLinkAddOn.cfg</configFile>
      <luciadMapOptions>Lightspeed</luciadMapOptions>
    </addon>
    <addon>
      <name>Recent Files</name>
      <class>com.luciad.lucy.addons.recentfiles.TLcyRecentFilesAddOn</class>
      <configFile>lucy/recentfiles/TLcyRecentFilesAddOn.cfg</configFile>
    </addon>
  </addons>
</addonConfiguration>

=== otcz/Vulcano2.0/src/com/company/addons_datarepository_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<addonConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="addons.xsd">
  <addons>
    
    <include>com/company/addons_gxy.xml</include>

    <addon>
      <name>Show ReadMe</name>
      <class>com.company.ShowReadMeAddOn</class>
      <configFile>com/company/DataRepositoryReadMe.cfg</configFile>
    </addon>
    <!--Add the data repository as the last addon, allowing the other addons
        to register their data source handlers and model decoders to the Lucy Environment-->
    <addon>
      <priority>9998</priority>
      <name>Data Repository</name>
      <class>com.company.DataRepositoryAddOn</class>
      <configFile>com/company/data_repository.cfg</configFile>
    </addon>



  </addons>
</addonConfiguration>
