=== otcz/Vulcano2.0/src/lucy/dafif/dafifLoader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="dafifLoaderConfiguration">
		<xs:annotation>
			<xs:documentation>Configuration file for TLcdDAFIFLoader</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dafifTypes" type="DAFIFTypes"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="DAFIFTypes">
    <xs:sequence>
      <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
		    <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="decoderClass" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
	</xs:complexType>
</xs:schema>

=== otcz/Vulcano2.0/src/lucy/dafif/dafifLoader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
DAFIF Edition 7 Loader configuration
-->
<dafifLoaderConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dafifLoader.xsd">
  <dafifTypes>
    <type>
      <name>Aerodrome</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFAerodromeDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Airspace</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFAirspaceDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Navaid</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFNavaidDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Special Use Airspace</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFSpecialUseAirspaceDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>ATS Route</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentATSRouteDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Runway</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentRunwayDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Heliport</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFHeliportDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Helipad</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentHelipadDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Holding</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentHoldingDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>ILS</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentILSDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Procedure</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentProcedureDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Military Training Route</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFMilitaryTrainingRouteDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Ortca</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFOrtcaDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Parachute Jump Area</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFParachuteJumpAreaDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Refueling Track</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFRefuelingTrackDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>VFR</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFVFRRouteDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Waypoint</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFWayPointDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Airport-Navaid</name>
      <decoderClass>com.luciad.format.dafif.decoder.TLcdDAFIFIndependentAerodromeNavaidDecoder</decoderClass>
    </type>
  </dafifTypes>

</dafifLoaderConfiguration>

=== otcz/Vulcano2.0/src/lucy/dafif/dafifLoaderEdition8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
DAFIF Edition 8 Loader configuration
 -->
<dafifLoaderConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dafifLoader.xsd">
  <dafifTypes>
    <type>
      <name>Aerodrome</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTAerodromeDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Airspace</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTAirspaceDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Navaid</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTNavaidDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Special Use Airspace</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTSpecialUseAirspaceDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>ATS Route</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentATSRouteDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Runway</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentRunwayDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Heliport</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTHeliportDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Helipad</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentHelipadDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Holding</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentHoldingDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>ILS</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentILSDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Procedure</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentProcedureDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Military Training Route</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTMilitaryTrainingRouteDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Ortca</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTOrtcaDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Parachute Jump Area</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTParachuteJumpAreaDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Refueling Track</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTRefuelingTrackDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>VFR</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTVFRRouteDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Waypoint</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTWayPointDecoder</decoderClass>
    </type>
  </dafifTypes>
  <dafifTypes>
    <type>
      <name>Airport-Navaid</name>
      <decoderClass>com.luciad.format.dafift.decoder.TLcdDAFIFTIndependentAerodromeNavaidDecoder</decoderClass>
    </type>
  </dafifTypes>

</dafifLoaderConfiguration>
